require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InformationConesController do

  # This should return the minimal set of attributes required to create a valid
  # InformationCone. As you add validations to InformationCone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InformationConesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all information_cones as @information_cones" do
      information_cone = InformationCone.create! valid_attributes
      get :index, {}, valid_session
      assigns(:information_cones).should eq([information_cone])
    end
  end

  describe "GET show" do
    it "assigns the requested information_cone as @information_cone" do
      information_cone = InformationCone.create! valid_attributes
      get :show, {:id => information_cone.to_param}, valid_session
      assigns(:information_cone).should eq(information_cone)
    end
  end

  describe "GET new" do
    it "assigns a new information_cone as @information_cone" do
      get :new, {}, valid_session
      assigns(:information_cone).should be_a_new(InformationCone)
    end
  end

  describe "GET edit" do
    it "assigns the requested information_cone as @information_cone" do
      information_cone = InformationCone.create! valid_attributes
      get :edit, {:id => information_cone.to_param}, valid_session
      assigns(:information_cone).should eq(information_cone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InformationCone" do
        expect {
          post :create, {:information_cone => valid_attributes}, valid_session
        }.to change(InformationCone, :count).by(1)
      end

      it "assigns a newly created information_cone as @information_cone" do
        post :create, {:information_cone => valid_attributes}, valid_session
        assigns(:information_cone).should be_a(InformationCone)
        assigns(:information_cone).should be_persisted
      end

      it "redirects to the created information_cone" do
        post :create, {:information_cone => valid_attributes}, valid_session
        response.should redirect_to(InformationCone.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved information_cone as @information_cone" do
        # Trigger the behavior that occurs when invalid params are submitted
        InformationCone.any_instance.stub(:save).and_return(false)
        post :create, {:information_cone => { "title" => "invalid value" }}, valid_session
        assigns(:information_cone).should be_a_new(InformationCone)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InformationCone.any_instance.stub(:save).and_return(false)
        post :create, {:information_cone => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested information_cone" do
        information_cone = InformationCone.create! valid_attributes
        # Assuming there are no other information_cones in the database, this
        # specifies that the InformationCone created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InformationCone.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => information_cone.to_param, :information_cone => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested information_cone as @information_cone" do
        information_cone = InformationCone.create! valid_attributes
        put :update, {:id => information_cone.to_param, :information_cone => valid_attributes}, valid_session
        assigns(:information_cone).should eq(information_cone)
      end

      it "redirects to the information_cone" do
        information_cone = InformationCone.create! valid_attributes
        put :update, {:id => information_cone.to_param, :information_cone => valid_attributes}, valid_session
        response.should redirect_to(information_cone)
      end
    end

    describe "with invalid params" do
      it "assigns the information_cone as @information_cone" do
        information_cone = InformationCone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InformationCone.any_instance.stub(:save).and_return(false)
        put :update, {:id => information_cone.to_param, :information_cone => { "title" => "invalid value" }}, valid_session
        assigns(:information_cone).should eq(information_cone)
      end

      it "re-renders the 'edit' template" do
        information_cone = InformationCone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InformationCone.any_instance.stub(:save).and_return(false)
        put :update, {:id => information_cone.to_param, :information_cone => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested information_cone" do
      information_cone = InformationCone.create! valid_attributes
      expect {
        delete :destroy, {:id => information_cone.to_param}, valid_session
      }.to change(InformationCone, :count).by(-1)
    end

    it "redirects to the information_cones list" do
      information_cone = InformationCone.create! valid_attributes
      delete :destroy, {:id => information_cone.to_param}, valid_session
      response.should redirect_to(information_cones_url)
    end
  end

end
